<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>preview</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../Sdl.MultiSelectComboBox/SdlCommunity.snk</AssemblyOriginatorKeyFile>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.0.2" />
    <PackageReference Include="TUnit" Version="0.*" />
    <PackageReference Include="TUnit.Assertions" Version="0.*" />
    <PackageReference Include="FlaUI.Core" Version="4.*" />
    <PackageReference Include="FlaUI.UIA3" Version="4.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiSelectComboBox.Example\Sdl.MultiSelectComboBox.Example.csproj" />
  </ItemGroup>

</Project>
